package com.project.location.model

import com.google.gson.annotations.SerializedName

data class UserModel(
  @SerializedName("verifyChanges") val verifyChanges: Map<String, Any>,
  @SerializedName("id") val id: String,
  @SerializedName("nik") val nik: String,
  @SerializedName("upliner_id") val uplinerId: String,
  @SerializedName("upliner2_id") val upliner2Id: String?,
  @SerializedName("upliner3_id") val upliner3Id: String?,
  @SerializedName("photo") val photo: String,
  @SerializedName("fullname") val fullname: String,
  @SerializedName("email") val email: String,
  @SerializedName("email_2") val email2: String?,
  @SerializedName("role_id") val roleId: String?,
  @SerializedName("division_name") val divisionName: String?,
  @SerializedName("department_name") val departmentName: String?,
  @SerializedName("unit_name") val unitName: String?,
  @SerializedName("employee_type_name") val employeeTypeName: String?,
  @SerializedName("position_name") val positionName: String?,
  @SerializedName("googleId") val googleId: String?,
  @SerializedName("employee_type_id") val employeeTypeId: String,
  @SerializedName("resetAttempts") val resetAttempts: Int?,
  @SerializedName("verifyToken") val verifyToken: String?,
  @SerializedName("verifyShortToken") val verifyShortToken: String?,
  @SerializedName("isVerified") val isVerified: Boolean,
  @SerializedName("is_enable_tracking") val isEnableTracking: Boolean,
  @SerializedName("is_user_project") val isUserProject: Boolean,
  @SerializedName("verifyExpires") val verifyExpires: String?,
  @SerializedName("resetToken") val resetToken: String?,
  @SerializedName("resetShortToken") val resetShortToken: String?,
  @SerializedName("resetExpires") val resetExpires: String?,
  @SerializedName("location_point_id") val locationPointId: String,
  @SerializedName("shifting_id") val shiftingId: String?,
  @SerializedName("job_level_id") val jobLevelId: String,
  @SerializedName("company_id") val companyId: String,
  @SerializedName("division_id") val divisionId: String,
  @SerializedName("job_departement_id") val jobDepartementId: String,
  @SerializedName("leave_amount") val leaveAmount: Int,
  @SerializedName("is_mobile") val isMobile: Boolean,
  @SerializedName("is_overtime") val isOvertime: Boolean?,
  @SerializedName("is_active") val isActive: Boolean,
  @SerializedName("shift_type") val shiftType: String,
  @SerializedName("required_selfie") val requiredSelfie: Boolean,
  @SerializedName("registered_from") val registeredFrom: String?,
  @SerializedName("hris_branch") val hrisBranch: String?,
  @SerializedName("hris_join_date") val hrisJoinDate: String?,
  @SerializedName("created_at") val createdAt: String,
  @SerializedName("updated_at") val updatedAt: String,
  @SerializedName("hierarchy_level") val hierarchyLevel: Int,
  @SerializedName("job_position_id") val jobPositionId: String,
  @SerializedName("project_id") val projectId: String?,
)
